# Generated by Django 5.0.6 on 2024-06-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='desc',
        ),
    ]
