# Generated by Django 5.0.6 on 2024-06-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_menuitem_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orderr',
        ),
    ]
