# Generated by Django 5.0.6 on 2024-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_order_orderr'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderr',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
