# Generated by Django 5.0.6 on 2024-06-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_orderr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderr',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
