# Generated by Django 5.0.6 on 2024-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orderr_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderr',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
