# Generated by Django 5.0.6 on 2024-06-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderr_is_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderr',
            old_name='is_shipped',
            new_name='ordergiven',
        ),
    ]
